name: "Spoolman Server"
description: "Run the latest stable version of Spoolman."
url: "https://github.com/Donkie/Spoolman"
slug: "spoolman_server"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
boot: auto
ports:
  8000/tcp: 8000
image: ghcr.io/donkie/spoolman
version: 0.15
